server:
  port: 8080
spring:
  rabbitmq:
    host: ${restaurant.rabbitmq.host}
    port: ${restaurant.rabbitmq.port}
    virtual-host: ${restaurant.rabbitmq.virtual-host}
    username: ${restaurant.rabbitmq.username}
    password: ${restaurant.rabbitmq.password}
  data:
    redis:
      host: ${restaurant.redis.host}
      port: ${restaurant.redis.port}
  application:
    name: Restaurant
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${restaurant.db.host}:3306/restaurant?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${restaurant.db.username}
    password: ${restaurant.db.password}
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
path:
  dish: ${restaurant.file.dish}
  inventory: ${restaurant.file.inventory}
  default: ${restaurant.file.default}
