restaurant:
  db:
    host: localhost
    username: root
    password: 2354818484
  redis:
    host: localhost
    port: 6379
  file:
    dish: D:/JAVA/Restaurant/src/main/resources/static/dish/
    inventory: D:/JAVA/Restaurant/src/main/resources/static/inventory/
    default: D:/JAVA/Restaurant/src/main/resources/static/default.jpg